DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL,
  PASSWORD CHAR(50) NOT NULL,
  DATE_SIGNUP DATETIME NOT NULL,
  DATE_SIGNIN DATETIME NOT NULL);
